// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/14fe4313f4a1cf69add3505a2ab1dbc690dc2116/google-apps-script/google-apps-script.mail.d.ts
declare namespace GoogleAppsScript {
  export module Mail {
    /**
     * Sends email.
     *
     * This service allows users to send emails with complete control over the
     *  content of the email. Unlike GmailApp, MailApp's sole purpose is sending email. MailApp cannot
     *  access a user's Gmail inbox.
     *
     * Changes to scripts written using GmailApp are more likely to trigger a re-authorization
     *  request from a user than MailApp scripts.
     */
    export interface MailApp {
      getRemainingDailyQuota(): Integer;
      sendEmail(message: Object): void;
      sendEmail(recipient: string, subject: string, body: string): void;
      sendEmail(recipient: string, subject: string, body: string, options: Object): void;
      sendEmail(to: string, replyTo: string, subject: string, body: string): void;
    }

  }
}

declare var MailApp: GoogleAppsScript.Mail.MailApp;
